name: final_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  sqflite : ^2.3.0
  provider: ^6.1.1
  path_provider: ^2.1.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.1
  firebase_auth: ^4.12.1
  http: ^1.0.0
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  path: ^1.8.3
  notifications: ^3.0.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  numberpicker: ^2.1.2
  url_launcher: ^6.2.1
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png



