// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXn2yozoElKAepNhdUcJvML7JGuiXrv5c',
    appId: '1:284120278833:web:40578ebb0f34fd490c3210',
    messagingSenderId: '284120278833',
    projectId: 'kagmjfinal',
    authDomain: 'kagmjfinal.firebaseapp.com',
    storageBucket: 'kagmjfinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPTrOKtLPbOuhF6rKfU23xnQhIqI7IR_s',
    appId: '1:284120278833:android:b79a02365a5039370c3210',
    messagingSenderId: '284120278833',
    projectId: 'kagmjfinal',
    storageBucket: 'kagmjfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gIqUIjZVSmzL6QLACkiVaGBI3gwbjGk',
    appId: '1:284120278833:ios:9f07d5e4db2e3b080c3210',
    messagingSenderId: '284120278833',
    projectId: 'kagmjfinal',
    storageBucket: 'kagmjfinal.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gIqUIjZVSmzL6QLACkiVaGBI3gwbjGk',
    appId: '1:284120278833:ios:6a2d77ceabe4ba460c3210',
    messagingSenderId: '284120278833',
    projectId: 'kagmjfinal',
    storageBucket: 'kagmjfinal.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
